### ISSUE TITLE
Tox tests fail with `no module named zope.testing`

### ISSUE THREAD

**Issue by msabramo** [gawel/gp.recipe.phantomjs#3]
```
$ tox -e py27
GLOB sdist-make: /Users/marca/dev/git-repos/gp.recipe.phantomjs/setup.py
py27 sdist-reinst: /Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/dist/gp.recipe.phantomjs-1.7.0.1.zip
py27 runtests: commands[0]
WARNING:test command found but not installed in testenv
  cmd: /bin/rm
  env: /Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27
Maybe forgot to specify a dependency?
py27 runtests: commands[1]
Creating directory '/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/parts'.
Develop: '/Users/marca/dev/git-repos/gp.recipe.phantomjs/.'
Installing casperjs.
Downloading https://phantomjs.googlecode.com/files/phantomjs-1.7.0-macosx.zip
casperjs: Extracting package to /Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/parts/casperjs
Downloading https://github.com/n1k0/casperjs/tarball/1.0.0-RC4
casperjs: Extracting package to /Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/parts/casperjs
py27 runtests: commands[2]
E.
======================================================================
ERROR: Failure: ImportError (No module named zope.testing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/marca/dev/git-repos/gp.recipe.phantomjs/gp/recipe/phantomjs/tests/test_docs.py", line 9, in <module>
    import zc.buildout.tests
  File "/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/lib/python2.7/site-packages/zc/buildout/tests.py", line 15, in <module>
    from zope.testing import renormalizing
ImportError: No module named zope.testing

----------------------------------------------------------------------
Ran 2 tests in 1.984s

FAILED (errors=1)
ERROR: InvocationError: '/Users/marca/dev/git-repos/gp.recipe.phantomjs/.tox/py27/bin/nosetests'
_________________________________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________________________________
ERROR:   py27: commands failed
```

**Comment by gawel** [comment]
I've just changed project's decription to deprecate this project. You can use gp.recipe.node to install phantomjs. Closing this old issue
